import type { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import { TurnkeyProvider, TurnkeyProviderConfig } from '@turnkey/react-wallet-kit'
import { ReactQueryProvider } from '@/components/react-query/react-query-provider'

import './globals.css'
import '@turnkey/react-wallet-kit/styles.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Exchange',
  description: 'Generated by create next app'
}

const turnkeyConfig: TurnkeyProviderConfig = {
  organizationId: process.env.NEXT_PUBLIC_ORGANIZATION_ID!,
  authProxyConfigId: process.env.NEXT_PUBLIC_AUTH_PROXY_CONFIG_ID!
}

export default function RootLayout({ children, modal }: Readonly<{ children: ReactNode; modal: ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <ReactQueryProvider>
          <TurnkeyProvider config={turnkeyConfig}>
            {children}
            {modal}
          </TurnkeyProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
